README.md:
	@echo "Generating README.md"
	@echo "This is a test" > README.md

WORK_FILE=work.txt

.PHONY: add-one
add-one:
	@echo "One" >> $(WORK_FILE)

.PHONY: add-two
add-two:
	@echo "Two" >> $(WORK_FILE)

.PHONY: add-three
add-three:
	@echo "Three" >> $(WORK_FILE)
